title: 'FLOOR33 Pictures'

header_pages:
  - index.md
  
remote_theme: b2a3e8/jekyll-theme-console

style: light 

footer: 'Join our beta version on <a href="https://discord.gg/beGdjPbp">[Discord]</a>'. </br> Floor33 is a scientific research channel which only for demonstrating the research demo. It is prohibited to use this open-source code for activities that harm the legitimate rights and interests of others (including but not limited to fraud, deception, infringement of others' portrait rights, reputation rights, etc.), or other behaviors that violate applicable laws and regulations or go against social ethics and good customs (including providing incorrect or false information, spreading pornographic, terrorist, and violent information, etc.). Otherwise, you may be liable for legal responsibilities.

