title: 'FLOOR33 Pictures'

header_pages:
  - index.md
  
remote_theme: b2a3e8/jekyll-theme-console

style: light 

footer: 'Join our beta version on <a href="https://discord.gg/rrayYqZ4tf">[Discord]</a>.'

